/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as PaymentStatusRouteImport } from './routes/payment-status'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerSignupRouteImport } from './routes/customer.signup'
import { Route as CustomerSigninRouteImport } from './routes/customer.signin'
import { Route as CustomerOutletsRouteImport } from './routes/customer.outlets'
import { Route as CustomerMyOrdersRouteImport } from './routes/customer.my-orders'
import { Route as CustomerMenuRouteImport } from './routes/customer.menu'
import { Route as AdminWalkinRouteImport } from './routes/admin.walkin'
import { Route as AdminVariantsRouteImport } from './routes/admin.variants'
import { Route as AdminSubcategoriesRouteImport } from './routes/admin.subcategories'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOutletsRouteImport } from './routes/admin.outlets'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminItemsRouteImport } from './routes/admin.items'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminImagesRouteImport } from './routes/admin.images'
import { Route as AdminDietaryRouteImport } from './routes/admin.dietary'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCuisinesRouteImport } from './routes/admin.cuisines'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBulkUploadRouteImport } from './routes/admin.bulk-upload'
import { Route as AdminAvailabilityRouteImport } from './routes/admin.availability'
import { Route as AdminAddonsRouteImport } from './routes/admin.addons'
import { Route as CustomerOrderDetailOrderIdRouteImport } from './routes/customer.order-detail.$orderId'
import { Route as CustomerItemDetailItemIdRouteImport } from './routes/customer.item-detail.$itemId'
import { Route as ApiPublicPhonepeWebhookRouteImport } from './routes/api/public/phonepe-webhook'
import { Route as AdminInvoiceOrderIdRouteImport } from './routes/admin.invoice.$orderId'

const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentStatusRoute = PaymentStatusRouteImport.update({
  id: '/payment-status',
  path: '/payment-status',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSignupRoute = CustomerSignupRouteImport.update({
  id: '/customer/signup',
  path: '/customer/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSigninRoute = CustomerSigninRouteImport.update({
  id: '/customer/signin',
  path: '/customer/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOutletsRoute = CustomerOutletsRouteImport.update({
  id: '/customer/outlets',
  path: '/customer/outlets',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerMyOrdersRoute = CustomerMyOrdersRouteImport.update({
  id: '/customer/my-orders',
  path: '/customer/my-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerMenuRoute = CustomerMenuRouteImport.update({
  id: '/customer/menu',
  path: '/customer/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalkinRoute = AdminWalkinRouteImport.update({
  id: '/admin/walkin',
  path: '/admin/walkin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVariantsRoute = AdminVariantsRouteImport.update({
  id: '/admin/variants',
  path: '/admin/variants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubcategoriesRoute = AdminSubcategoriesRouteImport.update({
  id: '/admin/subcategories',
  path: '/admin/subcategories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/admin/pricing',
  path: '/admin/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOutletsRoute = AdminOutletsRouteImport.update({
  id: '/admin/outlets',
  path: '/admin/outlets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminItemsRoute = AdminItemsRouteImport.update({
  id: '/admin/items',
  path: '/admin/items',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/admin/invoices',
  path: '/admin/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImagesRoute = AdminImagesRouteImport.update({
  id: '/admin/images',
  path: '/admin/images',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDietaryRoute = AdminDietaryRouteImport.update({
  id: '/admin/dietary',
  path: '/admin/dietary',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCuisinesRoute = AdminCuisinesRouteImport.update({
  id: '/admin/cuisines',
  path: '/admin/cuisines',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBulkUploadRoute = AdminBulkUploadRouteImport.update({
  id: '/admin/bulk-upload',
  path: '/admin/bulk-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAvailabilityRoute = AdminAvailabilityRouteImport.update({
  id: '/admin/availability',
  path: '/admin/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAddonsRoute = AdminAddonsRouteImport.update({
  id: '/admin/addons',
  path: '/admin/addons',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrderDetailOrderIdRoute =
  CustomerOrderDetailOrderIdRouteImport.update({
    id: '/customer/order-detail/$orderId',
    path: '/customer/order-detail/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerItemDetailItemIdRoute =
  CustomerItemDetailItemIdRouteImport.update({
    id: '/customer/item-detail/$itemId',
    path: '/customer/item-detail/$itemId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPhonepeWebhookRoute = ApiPublicPhonepeWebhookRouteImport.update({
  id: '/api/public/phonepe-webhook',
  path: '/api/public/phonepe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvoiceOrderIdRoute = AdminInvoiceOrderIdRouteImport.update({
  id: '/admin/invoice/$orderId',
  path: '/admin/invoice/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/payment-status': typeof PaymentStatusRoute
  '/splash': typeof SplashRoute
  '/admin/addons': typeof AdminAddonsRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/bulk-upload': typeof AdminBulkUploadRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/cuisines': typeof AdminCuisinesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dietary': typeof AdminDietaryRoute
  '/admin/images': typeof AdminImagesRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/outlets': typeof AdminOutletsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/subcategories': typeof AdminSubcategoriesRoute
  '/admin/variants': typeof AdminVariantsRoute
  '/admin/walkin': typeof AdminWalkinRoute
  '/customer/menu': typeof CustomerMenuRoute
  '/customer/my-orders': typeof CustomerMyOrdersRoute
  '/customer/outlets': typeof CustomerOutletsRoute
  '/customer/signin': typeof CustomerSigninRoute
  '/customer/signup': typeof CustomerSignupRoute
  '/admin/invoice/$orderId': typeof AdminInvoiceOrderIdRoute
  '/api/public/phonepe-webhook': typeof ApiPublicPhonepeWebhookRoute
  '/customer/item-detail/$itemId': typeof CustomerItemDetailItemIdRoute
  '/customer/order-detail/$orderId': typeof CustomerOrderDetailOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/payment-status': typeof PaymentStatusRoute
  '/splash': typeof SplashRoute
  '/admin/addons': typeof AdminAddonsRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/bulk-upload': typeof AdminBulkUploadRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/cuisines': typeof AdminCuisinesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dietary': typeof AdminDietaryRoute
  '/admin/images': typeof AdminImagesRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/outlets': typeof AdminOutletsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/subcategories': typeof AdminSubcategoriesRoute
  '/admin/variants': typeof AdminVariantsRoute
  '/admin/walkin': typeof AdminWalkinRoute
  '/customer/menu': typeof CustomerMenuRoute
  '/customer/my-orders': typeof CustomerMyOrdersRoute
  '/customer/outlets': typeof CustomerOutletsRoute
  '/customer/signin': typeof CustomerSigninRoute
  '/customer/signup': typeof CustomerSignupRoute
  '/admin/invoice/$orderId': typeof AdminInvoiceOrderIdRoute
  '/api/public/phonepe-webhook': typeof ApiPublicPhonepeWebhookRoute
  '/customer/item-detail/$itemId': typeof CustomerItemDetailItemIdRoute
  '/customer/order-detail/$orderId': typeof CustomerOrderDetailOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/payment-status': typeof PaymentStatusRoute
  '/splash': typeof SplashRoute
  '/admin/addons': typeof AdminAddonsRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/bulk-upload': typeof AdminBulkUploadRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/cuisines': typeof AdminCuisinesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dietary': typeof AdminDietaryRoute
  '/admin/images': typeof AdminImagesRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/outlets': typeof AdminOutletsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/subcategories': typeof AdminSubcategoriesRoute
  '/admin/variants': typeof AdminVariantsRoute
  '/admin/walkin': typeof AdminWalkinRoute
  '/customer/menu': typeof CustomerMenuRoute
  '/customer/my-orders': typeof CustomerMyOrdersRoute
  '/customer/outlets': typeof CustomerOutletsRoute
  '/customer/signin': typeof CustomerSigninRoute
  '/customer/signup': typeof CustomerSignupRoute
  '/admin/invoice/$orderId': typeof AdminInvoiceOrderIdRoute
  '/api/public/phonepe-webhook': typeof ApiPublicPhonepeWebhookRoute
  '/customer/item-detail/$itemId': typeof CustomerItemDetailItemIdRoute
  '/customer/order-detail/$orderId': typeof CustomerOrderDetailOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brands'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/payment-status'
    | '/splash'
    | '/admin/addons'
    | '/admin/availability'
    | '/admin/bulk-upload'
    | '/admin/categories'
    | '/admin/cuisines'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/dietary'
    | '/admin/images'
    | '/admin/invoices'
    | '/admin/items'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/outlets'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/reports'
    | '/admin/subcategories'
    | '/admin/variants'
    | '/admin/walkin'
    | '/customer/menu'
    | '/customer/my-orders'
    | '/customer/outlets'
    | '/customer/signin'
    | '/customer/signup'
    | '/admin/invoice/$orderId'
    | '/api/public/phonepe-webhook'
    | '/customer/item-detail/$itemId'
    | '/customer/order-detail/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brands'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/payment-status'
    | '/splash'
    | '/admin/addons'
    | '/admin/availability'
    | '/admin/bulk-upload'
    | '/admin/categories'
    | '/admin/cuisines'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/dietary'
    | '/admin/images'
    | '/admin/invoices'
    | '/admin/items'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/outlets'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/reports'
    | '/admin/subcategories'
    | '/admin/variants'
    | '/admin/walkin'
    | '/customer/menu'
    | '/customer/my-orders'
    | '/customer/outlets'
    | '/customer/signin'
    | '/customer/signup'
    | '/admin/invoice/$orderId'
    | '/api/public/phonepe-webhook'
    | '/customer/item-detail/$itemId'
    | '/customer/order-detail/$orderId'
  id:
    | '__root__'
    | '/'
    | '/brands'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/payment-status'
    | '/splash'
    | '/admin/addons'
    | '/admin/availability'
    | '/admin/bulk-upload'
    | '/admin/categories'
    | '/admin/cuisines'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/dietary'
    | '/admin/images'
    | '/admin/invoices'
    | '/admin/items'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/outlets'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/reports'
    | '/admin/subcategories'
    | '/admin/variants'
    | '/admin/walkin'
    | '/customer/menu'
    | '/customer/my-orders'
    | '/customer/outlets'
    | '/customer/signin'
    | '/customer/signup'
    | '/admin/invoice/$orderId'
    | '/api/public/phonepe-webhook'
    | '/customer/item-detail/$itemId'
    | '/customer/order-detail/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandsRoute: typeof BrandsRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  PaymentStatusRoute: typeof PaymentStatusRoute
  SplashRoute: typeof SplashRoute
  AdminAddonsRoute: typeof AdminAddonsRoute
  AdminAvailabilityRoute: typeof AdminAvailabilityRoute
  AdminBulkUploadRoute: typeof AdminBulkUploadRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCuisinesRoute: typeof AdminCuisinesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDietaryRoute: typeof AdminDietaryRoute
  AdminImagesRoute: typeof AdminImagesRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminItemsRoute: typeof AdminItemsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminOutletsRoute: typeof AdminOutletsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSubcategoriesRoute: typeof AdminSubcategoriesRoute
  AdminVariantsRoute: typeof AdminVariantsRoute
  AdminWalkinRoute: typeof AdminWalkinRoute
  CustomerMenuRoute: typeof CustomerMenuRoute
  CustomerMyOrdersRoute: typeof CustomerMyOrdersRoute
  CustomerOutletsRoute: typeof CustomerOutletsRoute
  CustomerSigninRoute: typeof CustomerSigninRoute
  CustomerSignupRoute: typeof CustomerSignupRoute
  AdminInvoiceOrderIdRoute: typeof AdminInvoiceOrderIdRoute
  ApiPublicPhonepeWebhookRoute: typeof ApiPublicPhonepeWebhookRoute
  CustomerItemDetailItemIdRoute: typeof CustomerItemDetailItemIdRoute
  CustomerOrderDetailOrderIdRoute: typeof CustomerOrderDetailOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-status': {
      id: '/payment-status'
      path: '/payment-status'
      fullPath: '/payment-status'
      preLoaderRoute: typeof PaymentStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/signup': {
      id: '/customer/signup'
      path: '/customer/signup'
      fullPath: '/customer/signup'
      preLoaderRoute: typeof CustomerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/signin': {
      id: '/customer/signin'
      path: '/customer/signin'
      fullPath: '/customer/signin'
      preLoaderRoute: typeof CustomerSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/outlets': {
      id: '/customer/outlets'
      path: '/customer/outlets'
      fullPath: '/customer/outlets'
      preLoaderRoute: typeof CustomerOutletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/my-orders': {
      id: '/customer/my-orders'
      path: '/customer/my-orders'
      fullPath: '/customer/my-orders'
      preLoaderRoute: typeof CustomerMyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/menu': {
      id: '/customer/menu'
      path: '/customer/menu'
      fullPath: '/customer/menu'
      preLoaderRoute: typeof CustomerMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/walkin': {
      id: '/admin/walkin'
      path: '/admin/walkin'
      fullPath: '/admin/walkin'
      preLoaderRoute: typeof AdminWalkinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/variants': {
      id: '/admin/variants'
      path: '/admin/variants'
      fullPath: '/admin/variants'
      preLoaderRoute: typeof AdminVariantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subcategories': {
      id: '/admin/subcategories'
      path: '/admin/subcategories'
      fullPath: '/admin/subcategories'
      preLoaderRoute: typeof AdminSubcategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/admin/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/outlets': {
      id: '/admin/outlets'
      path: '/admin/outlets'
      fullPath: '/admin/outlets'
      preLoaderRoute: typeof AdminOutletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/items': {
      id: '/admin/items'
      path: '/admin/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof AdminItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/admin/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/images': {
      id: '/admin/images'
      path: '/admin/images'
      fullPath: '/admin/images'
      preLoaderRoute: typeof AdminImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dietary': {
      id: '/admin/dietary'
      path: '/admin/dietary'
      fullPath: '/admin/dietary'
      preLoaderRoute: typeof AdminDietaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cuisines': {
      id: '/admin/cuisines'
      path: '/admin/cuisines'
      fullPath: '/admin/cuisines'
      preLoaderRoute: typeof AdminCuisinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bulk-upload': {
      id: '/admin/bulk-upload'
      path: '/admin/bulk-upload'
      fullPath: '/admin/bulk-upload'
      preLoaderRoute: typeof AdminBulkUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/availability': {
      id: '/admin/availability'
      path: '/admin/availability'
      fullPath: '/admin/availability'
      preLoaderRoute: typeof AdminAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/addons': {
      id: '/admin/addons'
      path: '/admin/addons'
      fullPath: '/admin/addons'
      preLoaderRoute: typeof AdminAddonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/order-detail/$orderId': {
      id: '/customer/order-detail/$orderId'
      path: '/customer/order-detail/$orderId'
      fullPath: '/customer/order-detail/$orderId'
      preLoaderRoute: typeof CustomerOrderDetailOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/item-detail/$itemId': {
      id: '/customer/item-detail/$itemId'
      path: '/customer/item-detail/$itemId'
      fullPath: '/customer/item-detail/$itemId'
      preLoaderRoute: typeof CustomerItemDetailItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/phonepe-webhook': {
      id: '/api/public/phonepe-webhook'
      path: '/api/public/phonepe-webhook'
      fullPath: '/api/public/phonepe-webhook'
      preLoaderRoute: typeof ApiPublicPhonepeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invoice/$orderId': {
      id: '/admin/invoice/$orderId'
      path: '/admin/invoice/$orderId'
      fullPath: '/admin/invoice/$orderId'
      preLoaderRoute: typeof AdminInvoiceOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandsRoute: BrandsRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  PaymentStatusRoute: PaymentStatusRoute,
  SplashRoute: SplashRoute,
  AdminAddonsRoute: AdminAddonsRoute,
  AdminAvailabilityRoute: AdminAvailabilityRoute,
  AdminBulkUploadRoute: AdminBulkUploadRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCuisinesRoute: AdminCuisinesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDietaryRoute: AdminDietaryRoute,
  AdminImagesRoute: AdminImagesRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminItemsRoute: AdminItemsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminOutletsRoute: AdminOutletsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSubcategoriesRoute: AdminSubcategoriesRoute,
  AdminVariantsRoute: AdminVariantsRoute,
  AdminWalkinRoute: AdminWalkinRoute,
  CustomerMenuRoute: CustomerMenuRoute,
  CustomerMyOrdersRoute: CustomerMyOrdersRoute,
  CustomerOutletsRoute: CustomerOutletsRoute,
  CustomerSigninRoute: CustomerSigninRoute,
  CustomerSignupRoute: CustomerSignupRoute,
  AdminInvoiceOrderIdRoute: AdminInvoiceOrderIdRoute,
  ApiPublicPhonepeWebhookRoute: ApiPublicPhonepeWebhookRoute,
  CustomerItemDetailItemIdRoute: CustomerItemDetailItemIdRoute,
  CustomerOrderDetailOrderIdRoute: CustomerOrderDetailOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
