// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

import { supabase } from './client';

// In a standard React SPA, we don't have a secure backend to hold a service role key.
// Instead, we alias the "admin" client to the standard authenticated client.
// This ensures that all requests carry the user's JWT for RLS policies.
export const supabaseAdmin = supabase;
