// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aynfbxixpviadworsbmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5bmZieGl4cHZpYWR3b3JzYm1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA5NjczMjYsImV4cCI6MjA5NjU0MzMyNn0.E9OwY2oMspfkQizA1Vheb4D0wa3tSAGWWMcBTPkD3bc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const memoryStorage = {
  getItem: () => null,
  setItem: () => undefined,
  removeItem: () => undefined,
};

const isBrowser = typeof window !== "undefined" && typeof window.localStorage !== "undefined";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isBrowser ? window.localStorage : memoryStorage,
    persistSession: isBrowser,
    autoRefreshToken: isBrowser,
    detectSessionInUrl: isBrowser,
  }
});